# generated by datamodel-codegen:
#   filename:  pxmetadata.yaml
#   timestamp: 2024-02-06T15:13:33+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class Attribute(BaseModel):
    column_name: Optional[str] = Field(None, alias="columnName")
    """
    name of column in dataset
    """
    code: Optional[str] = None
    """
    the code of the measurement
    """
    codelist_id: Optional[str] = Field(None, alias="codelistId")
    """
    A Link to a PxCodes document
    """


class LabelConstructionOption(Enum):
    """
    Construct label for codelist entry as text or code or text then code or code then text
    """

    code = "code"
    text = "text"
    code_text = "code_text"
    text_code = "text_code"


class PriceType(Enum):
    """
    Empty if not a price
    """

    current = "Current"
    fixed = "Fixed"


class Contact(BaseModel):
    """
    Contact information for statistics (name, email, phone)
    """

    phone: Optional[str] = None
    email: Optional[str] = None
    """
    Personal or functional
    """
    name: Optional[Dict[str, str]] = None
    """
    Name of contact in all languages. Personal or functional
    """
    raw: Optional[Dict[str, str]] = None
    """
    If this has value it replaces the 3 other fields, so they are ignored. Anything, will be put under contact as is.
    """


class AttachmentItem(BaseModel):
    dimension_code: str = Field(..., alias="dimensionCode")
    """
    The code of the dimension (found in config for time and measure)
    """
    value_code: str = Field(..., alias="valueCode")
    """
    The code of the Value
    """


class TimeDimension(BaseModel):
    column_name: Optional[str] = Field(None, alias="columnName")
    """
    name of column in dataset
    """
    time_period_format: Optional[str] = Field(None, alias="timePeriodFormat")
    """
    example: yyyy
    """
    label: Optional[Dict[str, str]] = None


class CellNote(BaseModel):
    """
    Note on a cell/subcube
    """

    attachment: List[AttachmentItem]
    """
    Attaches the text on a point/subcube of the cube. The array has one or zero entries for each dimension. No entry for a dimension means everything.
    """
    text: Dict[str, str]
    is_mandatory: bool = Field(..., alias="isMandatory")


class Note(BaseModel):
    text: Dict[str, str]
    is_mandatory: bool = Field(..., alias="isMandatory")


class CodedDimension(BaseModel):
    column_name: str = Field(..., alias="columnName")
    """
    name of column in dataset
    """
    code: Optional[str] = None
    """
    the code of the dimention( aka variable). Defaults to columName if missing
    """
    is_geo_variable_type: Optional[bool] = Field(False, alias="isGeoVariableType")
    """
    Geo variable or not
    """
    codelist_id: str = Field(..., alias="codelistId")
    """
    A Link to a PxCodes document
    """
    label_construction_option: Optional[LabelConstructionOption] = Field(
        LabelConstructionOption.text, alias="labelConstructionOption"
    )
    """
    Construct label for codelist entry as text or code or text then code or code then text
    """
    label: Optional[Dict[str, str]] = None
    doublecolumn: Optional[bool] = False
    """
    Applies only to some of the file-export formats. See DOUBLECOLUMN-keyword
    """
    notes: Optional[List[Note]] = None
    meta_id: Optional[List[str]] = Field(None, alias="metaId")
    """
    For MetaId keyword
    """


class Dimension(BaseModel):
    column_name: str = Field(..., alias="columnName")
    """
    name of column in dataset
    """
    code: Optional[str] = None
    """
    the code of the dimension (aka variable). Defaults to columnName if missing
    """
    is_geo_variable_type: Optional[bool] = Field(False, alias="isGeoVariableType")
    """
    Geo variable or not
    """
    label_construction_option: Optional[LabelConstructionOption] = Field(
        LabelConstructionOption.text, alias="labelConstructionOption"
    )
    """
    Construct label for dimension entries as text or code or text then code or code then text
    """
    label: Optional[Dict[str, str]] = None
    elimination_possible: Optional[bool] = Field(False, alias="eliminationPossible")
    elimination_code: Optional[str] = Field(None, alias="eliminationCode")
    doublecolumn: Optional[bool] = False
    notes: Optional[List[Note]] = None
    meta_id: Optional[List[str]] = Field(None, alias="metaId")
    """
    For MetaId keyword
    """


class Measurement(BaseModel):
    column_name: str = Field(..., alias="columnName")
    """
    name of column in dataset
    """
    code: Optional[str] = None
    """
    the code of the measurement. Defaults to columName if missing
    """
    label: Dict[str, str]
    show_decimals: Optional[int] = Field(None, alias="showDecimals")
    """
    number of decimal to use in output. Optional if defined at dataset level
    """
    precision: Optional[int] = None
    """
    Optional precision value for PRECISION keyword in PX file
    """
    price_type: Optional[PriceType] = Field(None, alias="priceType")
    """
    Empty if not a price
    """
    is_seasonally_adjusted: Optional[bool] = Field(False, alias="isSeasonallyAdjusted")
    is_workingdays_adjusted: Optional[bool] = Field(False, alias="isWorkingdaysAdjusted")
    aggregation_allowed: bool = Field(..., alias="aggregationAllowed")
    """
    Is it meaningfull to sum this measurement
    """
    base_period: Optional[Dict[str, str]] = Field(None, alias="basePeriod")
    """
    For index example: '1. kvartal 2010'
    """
    reference_period: Optional[Dict[str, str]] = Field(None, alias="referencePeriod")
    """
    Text with information on the reference period for the statistics.
    """
    rank: Optional[Dict[str, str]] = None
    """
    Sort order for measurement in dimension, document order is default
    """
    unit_of_measure: Dict[str, str] = Field(..., alias="unitOfMeasure")
    """
    Text including unit multiplier
    """
    notes: Optional[List[Note]] = None
    meta_id: Optional[List[str]] = Field(None, alias="metaId")
    """
    For MetaId keyword
    """


class Dataset(BaseModel):
    """
    Payload
    """

    table_id: str = Field(..., alias="tableId")
    """
    example: '07459' To be used as id in PxWeb Url
    """
    stored_decimals: Optional[int] = Field(None, alias="storedDecimals")
    """
    How many decimals should be stored in the PxFile. Default is the max number of decimals shown.
    """
    statistics_id: Optional[str] = Field(None, alias="statisticsId")
    """
    Id of group of tables in the registry of statistics. example: '8765'
    """
    last_updated: Optional[str] = Field(None, alias="last-updated")
    """
    Last updated date from metadata if provided.
    """
    data_file: Optional[str] = Field(None, alias="dataFile")
    """
    TODO: Er dette en filsti eller en url. required? Adress to the parquet-file with datadata
    """
    base_title: Dict[str, str] = Field(..., alias="baseTitle")
    """
    Text to which tableid is prefixed and _by_ variable list is appended. Is used for the CONTENTS keyword. example: no Utenrikshandel med varer
    """
    matrix: Optional[str] = None
    """
    Optional explicit override for MATRIX keyword. If omitted, auto-generates 'tab_' + tableId
    """
    decimals: Optional[int] = None
    """
    Optional explicit override for DECIMALS keyword. If omitted, auto-generates max(stored_decimals, show_decimals)
    """
    title: Optional[Dict[str, str]] = None
    """
    Optional explicit override for TITLE keyword by language. If omitted, auto-generates formula with dimensions
    """
    contents: Optional[Dict[str, str]] = None
    """
    Optional explicit override for CONTENTS keyword by language. If omitted, auto-generates 'tableId: baseTitle,'
    """
    units: Optional[Dict[str, str]] = None
    """
    Optional explicit override for global UNITS keyword by language. If omitted, auto-generates from measurements
    """
    subject_code: Optional[str] = Field(None, alias="subjectCode")
    """
    Optional explicit override for SUBJECT-CODE keyword. Takes precedence over pxstatistics if provided
    """
    subject_text: Optional[Dict[str, str]] = Field(None, alias="subjectText")
    """
    Subject area description by language. Used with subjectCode for SUBJECT-AREA keyword.
    """
    subjectarea: Optional[Dict[str, str]] = None
    """
    Optional explicit override for SUBJECT-AREA keyword by language. Takes precedence over pxstatistics if provided
    """
    update_frequency: Optional[Dict[str, str]] = Field(None, alias="updateFrequency")
    """
    Not in use. Must mean the same in all languages. example: Quarterly
    """
    upcoming_releases_dateformat: Optional[str] = Field("%Y%m%d %H:%M", alias="upcomingReleasesDateformat")
    """
    Format for datetime.strptime reading items from upcomingReleases. Default is the pxweb standard which is CCYYMMDD hh:mm
    """
    upcoming_releases: Optional[List[str]] = Field(None, alias="upcomingReleases")
    """
    List of dates. The first will be used for LAST-UPDATE, the next will be used for NEXT-UPDATE.
    """
    contacts: Optional[List[Contact]] = None
    """
    Contact information for statistics. Will be used for CONTACT keyword.
    """
    show_decimals: Optional[int] = Field(None, alias="showDecimals")
    """
    Optional explicit override for SHOWDECIMALS keyword. If omitted, uses min of measurement showDecimals
    """
    search_keywords: Optional[Dict[str, List[str]]] = Field(None, alias="searchKeywords")
    """
    Array of keywords by language for search. Is used for the SYNONYMS keyword. example:'{en: [External trade, export]}'
    """
    notes: Optional[List[Note]] = None
    cell_notes: Optional[List[CellNote]] = Field(None, alias="cellNotes")
    time_dimension: TimeDimension = Field(..., alias="timeDimension")
    coded_dimensions: Optional[List[CodedDimension]] = Field(None, alias="codedDimensions")
    """
    Also known as classification variables
    """
    dimensions: Optional[List[Dimension]] = Field(None, alias="dimensions")
    """
    Uncoded dimensions
    """
    measurements: List[Measurement]
    """
    Also known as content variables
    """
    meta_id: Optional[List[str]] = Field(None, alias="metaId")
    """
    For MetaId keyword
    """
    row_missing: Optional[str] = Field(".", alias="rowMissing")
    """
    Value to insert in data when row is missing.
    """
    cell_missing: Optional[str] = Field(".", alias="cellMissing")
    """
    Value to insert in data when cell is missing.
    """
    official_statistics: Optional[bool] = Field(False, alias="officialStatistics")
    copyright: Optional[bool] = False
    first_published: Optional[str] = Field(None, alias="firstPublished")
    """
    The date when the data cube was first published in the format CCYYMMDD hh:mm
    """
    attributes: Optional[List[Attribute]] = None


class PxMetadata(BaseModel):
    """
    Outer class
    """

    dataset: Dataset
    """
    Payload
    """
